version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    user: vscode
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/InternManagement:cached
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5000:5000'
      - '5001:5001'
  db:
    image: mysql:latest
    volumes:
      - db:/run/mysql
    expose:
      - 3306
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'InternDB'
      MYSQL_USER: 'InternAdmin'
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
volumes:
  db:
secrets:
  db_password:
    file: secrets/db_password_file
  db_root_password:
    file: secrets/db_root_file